
#ifndef VOXEL_TYPES_H_
#define VOXEL_TYPES_H_

enum {
	OBJ_BLOCK,	/* full block */
	OBJ_SLAB,	/* half block */
	OBJ_STAIRS,	/* stairs */
	OBJ_PANE,	/* thin pane in the middle */
	OBJ_FLUID,	/* object for flowsims (debug only) */
	OBJ_COUNT
};

enum {
	MAT_DIRT,
	MAT_GRASS,
	MAT_LIMESTONE = 0x10,
	MAT_LIMESTONE_COBBLE,
	MAT_LIMESTONE_LBRICK,
	MAT_LIMESTONE_SBRICK,
	MAT_LIMESTONE_TILE,
	MAT_LIMESTONE_COLUMN,
	MAT_LIMESTONE_BLOCK,
	MAT_SANDSTONE = 0x20,
	MAT_SANDSTONE_COBBLE,
	MAT_SANDSTONE_LBRICK,
	MAT_SANDSTONE_SBRICK,
	MAT_SANDSTONE_TILE,
	MAT_SANDSTONE_COLUMN,
	MAT_SANDSTONE_BLOCK,
	MAT_MARBLE = 0x30,
	MAT_MARBLE_COBBLE,
	MAT_MARBLE_LBRICK,
	MAT_MARBLE_SBRICK,
	MAT_MARBLE_TILE,
	MAT_MARBLE_COLUMN,
	MAT_MARBLE_BLOCK,
	MAT_GRANITE = 0x40,
	MAT_GRANITE_COBBLE,
	MAT_GRANITE_LBRICK,
	MAT_GRANITE_SBRICK,
	MAT_GRANITE_TILE,
	MAT_GRANITE_COLUMN,
	MAT_GRANITE_BLOCK,
	MAT_BASALT = 0x50,
	MAT_BASALT_COBBLE,
	MAT_BASALT_LBRICK,
	MAT_BASALT_SBRICK,
	MAT_BASALT_TILE,
	MAT_BASALT_COLUMN,
	MAT_BASALT_BLOCK,
	MAT_SLATE = 0x60,
	MAT_SLATE_COBBLE,
	MAT_SLATE_LBRICK,
	MAT_SLATE_SBRICK,
	MAT_SLATE_TILE,
	MAT_SLATE_COLUMN,
	MAT_SLATE_BLOCK,
	MAT_CLAY = 0x70,
	MAT_CLAY_COBBLE,
	MAT_CLAY_LBRICK,
	MAT_CLAY_SBRICK,
	MAT_CLAY_TILE,
	MAT_CLAY_COLUMN,
	MAT_CLAY_BLOCK,
	MAT_WOOD1 = 0x80,
	MAT_WOOD1_CRATE,
	MAT_WOOD1_WORKBENCH,
	MAT_WOOD1_PIPE,
	MAT_WOOD2 = 0x90,
	MAT_WOOD2_CRATE,
	MAT_WOOD2_WORKBENCH,
	MAT_WOOD2_PIPE,
	MAT_WOOD3 = 0xA0,
	MAT_WOOD3_CRATE,
	MAT_WOOD3_WORKBENCH,
	MAT_WOOD3_PIPE,
	MAT_WOOD4 = 0xB0,
	MAT_WOOD4_CRATE,
	MAT_WOOD4_WORKBENCH,
	MAT_WOOD4_PIPE,
	MAT_WOOD5 = 0xC0,
	MAT_WOOD5_CRATE,
	MAT_WOOD5_WORKBENCH,
	MAT_WOOD5_PIPE,
	MAT_WOOD6 = 0xD0,
	MAT_WOOD6_CRATE,
	MAT_WOOD6_WORKBENCH,
	MAT_WOOD6_PIPE,
	MAT_WOOD7 = 0xE0,
	MAT_WOOD7_CRATE,
	MAT_WOOD7_WORKBENCH,
	MAT_WOOD7_PIPE,
	MAT_COUNT,
};

enum {
	SHAPE_NONE,
	SHAPE_BLOCK_DN,
	SHAPE_BLOCK_UP,
	SHAPE_BLOCK_LF,
	SHAPE_BLOCK_RT,
	SHAPE_BLOCK_BK,
	SHAPE_BLOCK_FT,
	SHAPE_SLAB_DN,
	SHAPE_SLAB_UP,
	SHAPE_SLAB_LF,
	SHAPE_SLAB_RT,
	SHAPE_SLAB_BK,
	SHAPE_SLAB_FT,
	SHAPE_PANE_X,
	SHAPE_PANE_Y,
	SHAPE_PANE_Z,
	SHAPE_STAIRS_DF,
	SHAPE_STAIRS_DL,
	SHAPE_STAIRS_DB,
	SHAPE_STAIRS_DR,
	SHAPE_STAIRS_UF,
	SHAPE_STAIRS_UL,
	SHAPE_STAIRS_UB,
	SHAPE_STAIRS_UR,
	SHAPE_COUNT,
};

enum {
	FACE_FT,
	FACE_LF,
	FACE_BK,
	FACE_RT,
	FACE_UP,
	FACE_DN,
};

extern const char *obj_names[];
extern const char *mat_names[];
extern const char *face_names[];
extern const char *shape_names[];

extern const int mat_is_workbench[];
extern const int mat_capacity[];

#endif
