
#ifndef VOXEL_TYPES_H_
#define VOXEL_TYPES_H_

enum {
	OBJ_BLOCK,	/* full block */
	OBJ_SLAB,	/* half block */
	OBJ_STAIRS,	/* stairs */
	OBJ_PANE,	/* thin pane in the middle */
	OBJ_FLUID,	/* object for flowsims (debug only) */
	OBJ_COUNT
};

enum {
	MAT_LIMESTONE,
	MAT_DIRT,
	MAT_WOOD,
	MAT_LIMESTONE_TILE,
	MAT_GRASS,
	MAT_LIMESTONE_LBRICK,
	MAT_WORKBENCH,
	MAT_CRATE,
	MAT_PIPE,
	MAT_LIMESTONE_COBBLE,
	MAT_LIMESTONE_SBRICK,
	MAT_LIMESTONE_COLUMN,
	MAT_LIMESTONE_BLOCK,
	MAT_SANDSTONE,
	MAT_SANDSTONE_COBBLE,
	MAT_SANDSTONE_LBRICK,
	MAT_SANDSTONE_SBRICK,
	MAT_SANDSTONE_TILE,
	MAT_SANDSTONE_COLUMN,
	MAT_SANDSTONE_BLOCK,
	MAT_MARBLE,
	MAT_MARBLE_COBBLE,
	MAT_MARBLE_LBRICK,
	MAT_MARBLE_SBRICK,
	MAT_MARBLE_TILE,
	MAT_MARBLE_COLUMN,
	MAT_MARBLE_BLOCK,
	MAT_GRANITE,
	MAT_GRANITE_COBBLE,
	MAT_GRANITE_LBRICK,
	MAT_GRANITE_SBRICK,
	MAT_GRANITE_TILE,
	MAT_GRANITE_COLUMN,
	MAT_GRANITE_BLOCK,
	MAT_BASALT,
	MAT_BASALT_COBBLE,
	MAT_BASALT_LBRICK,
	MAT_BASALT_SBRICK,
	MAT_BASALT_TILE,
	MAT_BASALT_COLUMN,
	MAT_BASALT_BLOCK,
	MAT_SLATE,
	MAT_SLATE_COBBLE,
	MAT_SLATE_LBRICK,
	MAT_SLATE_SBRICK,
	MAT_SLATE_TILE,
	MAT_SLATE_COLUMN,
	MAT_SLATE_BLOCK,
	MAT_CLAY,
	MAT_CLAY_COBBLE,
	MAT_CLAY_LBRICK,
	MAT_CLAY_SBRICK,
	MAT_CLAY_TILE,
	MAT_CLAY_COLUMN,
	MAT_CLAY_BLOCK,
	MAT_WOOD_1,
	MAT_WOOD_2,
	MAT_WOOD_3,
	MAT_WOOD_4,
	MAT_WOOD_5,
	MAT_WOOD_6,
	MAT_WOOD_7,
	MAT_COUNT,
};

enum {
	SHAPE_NONE,
	SHAPE_BLOCK_DN,
	SHAPE_BLOCK_UP,
	SHAPE_BLOCK_LF,
	SHAPE_BLOCK_RT,
	SHAPE_BLOCK_BK,
	SHAPE_BLOCK_FT,
	SHAPE_SLAB_DN,
	SHAPE_SLAB_UP,
	SHAPE_SLAB_LF,
	SHAPE_SLAB_RT,
	SHAPE_SLAB_BK,
	SHAPE_SLAB_FT,
	SHAPE_PANE_X,
	SHAPE_PANE_Y,
	SHAPE_PANE_Z,
	SHAPE_STAIRS_DF,
	SHAPE_STAIRS_DL,
	SHAPE_STAIRS_DB,
	SHAPE_STAIRS_DR,
	SHAPE_STAIRS_UF,
	SHAPE_STAIRS_UL,
	SHAPE_STAIRS_UB,
	SHAPE_STAIRS_UR,
	SHAPE_COUNT,
};

enum {
	FACE_FT,
	FACE_LF,
	FACE_BK,
	FACE_RT,
	FACE_UP,
	FACE_DN,
};

extern const char *obj_names[];
extern const char *mat_names[];
extern const char *face_names[];
extern const char *shape_names[];

#endif
